name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install, Build, and Export
        run: |
          npm ci
          npm run build
          npm run export
        env:
          NEXT_PUBLIC_REPO_NAME: ${{ github.event.repository.name }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          BRANCH: gh-pages
          FOLDER: out
          CLEAN: true
